//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Studio_Booking
{
    public partial class Profile
    {
        /// <summary>
        /// lblName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblName;

        /// <summary>
        /// lblEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmail;

        /// <summary>
        /// lblUserId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserId;
    }
}

